use_frameworks!
#source 'https://github.com/CocoaPods/Specs.git'
#pod 'DemoOpensSSL’,’0.1.16’
source 'https://nostanle:6fddae2f2a6b2839b839e604ac12149c67e2a504@github.ibm.com/nostanle/imf-client-sdk-specs-inhouse.git'
pod 'IBMMobileFirstPlatformFoundation'
pod 'IBMMobileFirstPlatformFoundationOpenSSLUtils'