use_frameworks!
#source 'https://github.com/CocoaPods/Specs.git'
#pod 'DemoOpensSSL’,’0.1.16’
source 'https://github.ibm.com/nostanle/imf-client-sdk-specs-inhouse.git'
pod 'IBMMobileFirstPlatformFoundation'
pod 'IBMMobileFirstPlatformFoundationOpenSSLUtils'